spring.application.name=load-balancing-gateway
server.port=8083

spring.cloud.gateway.server.webflux.routes[0].id=load-balanced-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://my-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/service/**